### ISSUE TITLE
Add Python environment setup

### ISSUE THREAD

**Issue by jeanmarcalkazzi** [zijinoier/Hetero-MAPF#1]
## Description

This feature involves adding a `requirements.txt` file with appropriate libraries needed for the visualization script.  
Additional info will be needed in the `README.md` to setup Python correctly.

## Proposals

Given that it is a very simple script and only used for visualization, having a virtual environment is not necessary and the few libraries needed (numpy, matplotlib, and PyQt5) can be directly installed from the `requirements.txt` file.

**Comment by zijinoier** [comment]
Already merge it to `dev` branch.
